### ISSUE TITLE
Add a New User: tastrax

### ISSUE THREAD

**Issue by tastrax** [OSM-de/wmw#10]
# Add a new User to the Map

tastrax

## Area of local knowledge

{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[142.998046875,-39.30029918615028],[144.8876953125,-43.580390855607845],[158.33496093749997,-55.07836723201513],[159.609375,-54.85131525968607],[148.53515625,-39.266284422130646],[142.998046875,-39.30029918615028]]]}}]}

**Comment by kmpoppe** [comment]
https://wmw.webmapping.cyou/?map=-42.71205,146.21697&zoom=4
