### ISSUE TITLE
Add a New User: endim8

### ISSUE THREAD

**Issue by endim8** [OSM-de/wmw#4]
# Add a new User to the Map

## OSM Username

Please provide your OpenStreetMap username (Casing is important!): endim8

## Area of local knowledge
https://gist.github.com/endim8/1bc9e1b0a2ec1e4f90fa4ea1c65281c4

**Comment by endim8** [comment]
thank you for this, it seems very useful :)

**Comment by kmpoppe** [comment]
Thanks. Let's see if we get a sizable number of entries that it becomes helpful for anyone :)

**Comment by kmpoppe** [comment]
Closed with cc56798.
https://wmw.webmapping.cyou/?map=51.47779,0.01879&zoom=11.00
:)
