### ISSUE TITLE
Add a New User: heilbron

### ISSUE THREAD

**Issue by sheilbronn** [OSM-de/wmw#5]
# Add a new User to the Map

## OSM Username

heilbron

## Area of local knowledge

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "stroke": "#555555",
        "stroke-width": 2,
        "stroke-opacity": 1,
        "fill": "#555555",
        "fill-opacity": 0.5
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              11.480798721313477,
              48.08593460398343
            ],
            [
              11.46449089050293,
              48.04813616275618
            ],
            [
              11.510066986083984,
              48.040905985397316
            ],
            [
              11.528863906860352,
              48.05886479329051
            ],
            [
              11.537961959838867,
              48.065232067568
            ],
            [
              11.537017822265625,
              48.079627234277204
            ],
            [
              11.540107727050781,
              48.09069328919107
            ],
            [
              11.52637481689453,
              48.092355858538156
            ],
            [
              11.52637481689453,
              48.10422160272917
            ],
            [
              11.521568298339842,
              48.101642326083535
            ],
            [
              11.518735885620117,
              48.09579548653672
            ],
            [
              11.493673324584961,
              48.08971865458321
            ],
            [
              11.480798721313477,
              48.08593460398343
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              11.572036743164062,
              48.17979419621881
            ],
            [
              11.57504081726074,
              48.179880043399855
            ],
            [
              11.576628684997559,
              48.19641725163422
            ],
            [
              11.563582420349121,
              48.19581651222436
            ],
            [
              11.566457748413086,
              48.175158234958054
            ],
            [
              11.572036743164062,
              48.17979419621881
            ]
          ]
        ]
      }
    }
  ]
}

**Comment by kmpoppe** [comment]
https://wmw.webmapping.cyou/?map=48.07294,11.51594&zoom=9.00
:-)
