### ISSUE TITLE
Add a New User: gzin

### ISSUE THREAD

**Issue by gzin** [OSM-de/wmw#6]
# Add a new User to the Map

## OSM Username

Please provide your OpenStreetMap username (Casing is important!): gzin

## Area of local knowledge

Please provide a link to a Gist or put the contents of the GeoJSON directly.
https://gist.github.com/gzin/39d306a281d4c866880f73171244c474

**Comment by kmpoppe** [comment]
https://wmw.webmapping.cyou/?map=48.22467,13.97461&zoom=10.00
