### ISSUE TITLE
Add a New User: Karthoo

### ISSUE THREAD

**Issue by Karthoo** [OSM-de/wmw#7]
# Add a new User to the Map

## OSM Username

Karthoo

## Area of local knowledge

[Please provide a link to a Gist or put the contents of the GeoJSON directly.](https://gist.github.com/Karthoo/a06c0cdf7650d097a23046a51711f5c6)

**Comment by kmpoppe** [comment]
https://wmw.webmapping.cyou/?map=48.48020,7.83875&zoom=8.00
