### ISSUE TITLE
Add a New User: juminet

### ISSUE THREAD

**Issue by nobohan** [OSM-de/wmw#8]
# Add a new User to the Map

## OSM Username

Please provide your OpenStreetMap username (Casing is important!): juminet

## Area of local knowledge

Please provide a link to a Gist or put the contents of the GeoJSON directly.

https://gist.github.com/nobohan/c1d31e4ce9af8268a0dedfe589d3199f

**Comment by kmpoppe** [comment]
https://wmw.webmapping.cyou/?map=49.80963,5.42725&zoom=8.00
