### ISSUE TITLE
Add a New User: whatismoss

### ISSUE THREAD

**Issue by 32Vache** [OSM-de/wmw#9]
# Add a new User to the Map

## OSM Username

whatismoss

## Area of local knowledge

`{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"shape":"Polygon","name":"Unnamed Layer","category":"default"},"geometry":{"type":"Polygon","coordinates":[[[2.945473,50.432675],[2.945738,50.430247],[2.944229,50.428046],[2.942147,50.427472],[2.938657,50.424734],[2.938907,50.423243],[2.940238,50.421439],[2.94204,50.421931],[2.943814,50.419885],[2.942512,50.417779],[2.94847,50.416553],[2.949851,50.414361],[2.949543,50.411936],[2.946696,50.410564],[2.948384,50.409283],[2.939987,50.405586],[2.942555,50.404036],[2.94646,50.406165],[2.948556,50.406863],[2.953384,50.405108],[2.953842,50.403658],[2.962368,50.398201],[2.962654,50.398543],[2.96495,50.402778],[2.966874,50.401151],[2.967374,50.399569],[2.969699,50.398028],[2.970843,50.396477],[2.973139,50.396313],[2.974255,50.397061],[2.973483,50.398183],[2.971852,50.398278],[2.970693,50.397923],[2.969041,50.399104],[2.97065,50.399455],[2.973883,50.399869],[2.974756,50.40126],[2.967167,50.405846],[2.96751,50.407227],[2.971838,50.405486],[2.974806,50.404246],[2.978003,50.407465],[2.980063,50.408322],[2.982509,50.411635],[2.982917,50.413304],[2.982373,50.415555],[2.979863,50.416594],[2.976809,50.417665],[2.974992,50.415487],[2.976694,50.41483],[2.972474,50.411047],[2.969584,50.412369],[2.96942,50.413363],[2.968397,50.414243],[2.971544,50.418034],[2.973375,50.420591],[2.966716,50.421539],[2.963669,50.422277],[2.96025,50.420915],[2.958369,50.421357],[2.959435,50.42302],[2.957654,50.423376],[2.95671,50.422938],[2.955222,50.424105],[2.955236,50.425891],[2.953091,50.429081],[2.953899,50.429837],[2.956681,50.4314],[2.955902,50.432457],[2.95337,50.432976],[2.952211,50.432019],[2.945473,50.432675]]]},"id":"26033819-170c-4081-9bf4-0a3bcc41c9a2"}]}`

**Comment by kmpoppe** [comment]
https://wmw.webmapping.cyou/?map=50.41560,2.95603&zoom=11
